//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movies.Backend.Core.UseCases.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OurMovie
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public Nullable<int> RunningTime { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Rating { get; set; }
        public string Discription { get; set; }
        public Nullable<int> BookingId { get; set; }
    }
}
